name: sagaeat
description: "SagaEat - Logiciel SaaS pou Restoran & Fast Food ann Ayiti."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  dio: ^5.8.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.4
  permission_handler: ^11.3.0
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

# ── App Icon Generator ─────────────────────────────────────────────────────────
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/iconsagaeat.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/iconsagaeat.png"
    background_color: "#F55623"
    theme_color: "#F55623"
  windows:
    generate: true
    image_path: "assets/images/iconsagaeat.png"
    icon_size: 48

# ── Native Splash Screen ───────────────────────────────────────────────────────
flutter_native_splash:
  color: "#F55623"
  image: assets/images/logo2sagaeat.png
  android_12:
    color: "#F55623"
    image: assets/images/logo2sagaeat.png
    icon_background_color: "#F55623"
  ios: true
  android: true
  web: false
  fullscreen: true

# ── Flutter ────────────────────────────────────────────────────────────────────
flutter:
  uses-material-design: true

  assets:
    - assets/images/
